language: ruby
cache: bundler

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build
  - docker-compose run app

notifications:
  slack:
    secure: HbbAFp3EZjRAgFU/9gjohEf29n2/LEEtMk9QBVjN0OtI6Ft0VGI7fHmyEVhhZIb7lv91HAZC848WGH502+R8kHkWnXbRmF2xaIiGesxktM7dVwIrR/lQ2gIMs+6N6WcNdrVB4JXIWn9hhKitT7HBlSU1AZBguo1WNqlLJjdFNTVqIVvpxq4OPN/MZtejvZe7Da3kmE04NE09x9dMoaj4YmKiwNpEf9h+QVxZgVnoyCi3Y1JmpuQbad5Zxjnru2+BzgBXgfQKG8p1eQcNNtpdkJGif+7H+QxDjMXAgU666hJYwQWIdLUKfoeL6AxZ9mI/jx0zXQikMrZhjuJRxix+QLnns8yZENFQ0XVkbiSj9yzJY72IEomARklUC6p/Tvaui3uYnuXSQVCOt1bd4CTq5pp0lhOOlVFhLKW4kkQju8xRGQm91wHi86BixLsncc1sruWMcAByJRBGRCYaOmvP+tVJZx8oXFMXPZDY+tc3nS9kzGZDh7xvrTBQDTYYx/Jgg37NWeNjWd9A0pu6s5EPbpiAV2M4aaaGNue7TkcuPTFiLklyuJXhTfJJ1pw3e3KHCoI1/I4udyQYuvBZhke7D175npi0AWC6xV5oq6jtScNcR5sXhSPg2tp+TXfn+cJYC8jIP0sZIS4JGf3YPAP5edsBB9PL/XXVcq2PJXzpTk0=
