sudo: required
language: ruby

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - git clean -xdf
  - docker build -t u6kapps/crawline -f Dockerfile.production .
  - docker-compose -f docker-compose.production.yml up -d
  - docker-compose -f docker-compose.production.yml exec app rails test
  - docker-compose -f docker-compose.production.yml down -v

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker tag u6kapps/crawline u6kapps/crawline:$TRAVIS_TAG;
      docker push u6kapps/crawline;
    else
      echo skip docker push;
    fi
