version: '3'

services:
  app:
    build: .
    volumes:
      - ".:/var/myapp"
    depends_on:
      - "s3"
    command: /bin/sh -c "bundle install && rake spec"
  s3:
    image: minio/minio
    volumes:
      - "s3:/export"
    command: server /export

volumes:
  s3:
    driver: local
