version: '3'

services:
  app:
    image: u6kapps/crawline
    environment:
      - "RAILS_ENV=production"
      - "RAILS_LOG_TO_STDOUT=true"
      - "SECRET_KEY_BASE=xxx"
      - "DB_HOST=db"
      - "DB_USERNAME=db_user"
      - "DB_PASSWORD=db_pass"
      - "DB_DATABASE=db"
      - "S3_ENDPOINT=http://s3:9000"
      - "S3_REGION=my-region"
      - "S3_ACCESS_KEY=s3_access_key"
      - "S3_SECRET_KEY=s3_secret_key"
      - "S3_BUCKET=test.crawline"
      - "S3_FOLDER=crawline"
    depends_on:
      - "db"
      - "s3"
    ports:
      - "3000:3000"
  db:
    image: postgres:10
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_pass"
      - "POSTGRES_DB=db"
    volumes:
      - "db:/var/lib/postgresql/data"
  s3:
    image: minio/minio
    volumes:
      - "s3:/export"
    environment:
      - "MINIO_ACCESS_KEY=s3_access_key"
      - "MINIO_SECRET_KEY=s3_secret_key"
      - "MINIO_REGION=my-region"
    command: server /export

volumes:
  db:
    driver: local
  s3:
    driver: local
