version: '3'

services:
  app:
    build: .
    environment:
      - "RAILS_ENV=development"
      - "DB_HOST=db"
      - "DB_USERNAME=db_user"
      - "DB_PASSWORD=db_pass"
      - "DB_DATABASE=db"
      - "S3_ACCESS_KEY=s3-access-key"
      - "S3_SECRET_KEY=s3-secret-key"
      - "S3_REGION=my-region"
      - "S3_BUCKET=test.crawline"
      - "S3_ENDPOINT_URL=http://s3:9000"
      - "S3_FORCE_PATH_STYLE=true"
    volumes:
      - ".:/var/myapp"
    depends_on:
      - "db"
      - "s3"
    ports:
      - "3000:3000"
  db:
    image: postgres:10
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_pass"
      - "POSTGRES_DB=db"
    volumes:
      - "db:/var/lib/postgresql/data"
  s3:
    image: minio/minio
    volumes:
      - "s3:/export"
    environment:
      - "MINIO_ACCESS_KEY=s3-access-key"
      - "MINIO_SECRET_KEY=s3-secret-key"
      - "MINIO_REGION=my-region"
    command: server /export

volumes:
  db:
    driver: local
  s3:
    driver: local
